### ISSUE TITLE
Python scripts don't work with python v3.7

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp-classes#1]
Could it be that the scripts only supports an older v2.x version? And is this by intention?

**Comment by grodansparadis** [comment]
No of course it is good if Python 3 also is supported even if it probably does not affect many.   I noticed "print" was changed and the new syntax works in 2.7 also. Should be not big deal to fix..

**Comment by BlueAndi** [comment]
Yes, I stumbled over "print". ;-) I fixed it locally for the the js relevant scripts. Pull request will follow.

**Comment by grodansparadis** [comment]
:)
